# -*- coding: utf-8 -*-
"""DATASCIENCE CASESTUDY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t12A6mRiTPLSBUsarQNyPEdWLpXeR9PU

The extracted CSV dataset was uploaded into the Google Colab environment for further processing using Python.
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("IMDB Dataset.csv")

df.head()

"""The dataset was loaded using the pandas library. Initial exploration was performed using functions like head() and info() to understand the structure, number of records, and data types. The dataset contains 50,000 reviews with balanced sentiment classes.

verify the data
"""

df.info()

"""Check sentiment distribution"""

df['sentiment'].value_counts()

"""Data Cleaning

Text data was cleaned using string manipulation techniques such as lowercasing and regular expressions. HTML tags, special characters, and extra spaces were removed to normalize the textual data and improve analysis quality.
"""

import re

def clean_text(text):
    text = text.lower()                         # convert to lowercase
    text = re.sub(r"<.*?>", "", text)           # remove HTML tags
    text = re.sub(r"[^a-z\s]", "", text)        # remove punctuation & numbers
    text = re.sub(r"\s+", " ", text).strip()    # remove extra spaces
    return text

df['clean_review'] = df['review'].apply(clean_text)

df[['review', 'clean_review']].head()

"""The cleaned textual data was transformed into structured numerical format using TF-IDF vectorization. This technique assigns weights to words based on their frequency and importance, enabling machine learning models to process textual data effectively."""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['clean_review'])

print(X.shape)

"""Handling Large Volumes of Streaming Data

To handle large volumes of streaming data, distributed systems such as Apache Kafka and Apache Spark Streaming can be used. Kafka enables real-time data ingestion, while Spark processes data at scale. These technologies allow efficient, scalable, and real-time sentiment analysis for continuously generated data.

In real-world applications, sentiment analysis often involves processing streaming data, which is continuously generated from sources such as user reviews, feedback systems, and online platforms. Unlike static datasets, streaming data requires real-time processing and scalable systems.

To handle such large volumes of data, distributed streaming technologies are used. Apache Kafka is commonly used for real-time data ingestion, where it collects and streams incoming data efficiently. For processing this data, Apache Spark Streaming can be used, as it allows fast and scalable analysis of large datasets.

These systems ensure high throughput, fault tolerance, and scalability, enabling organizations to perform real-time sentiment analysis on continuously generated data. This approach is widely used in modern data-driven applications to handle big data efficiently.

**Visualization**

Create a new feature
"""

df['review_length'] = df['clean_review'].apply(len)
df.head()

"""Histogram (Distribution)"""

import matplotlib.pyplot as plt

plt.hist(df['review_length'], bins=50)
plt.title("Distribution of Review Length")
plt.xlabel("Length")
plt.ylabel("Frequency")
plt.show()

"""Boxplot (Outliers)"""

plt.boxplot(df['review_length'])
plt.title("Boxplot of Review Length")
plt.show()

"""Scatter Plot (Relation)"""

df['sentiment_num'] = df['sentiment'].map({'positive':1, 'negative':0})

plt.scatter(df['review_length'], df['sentiment_num'], alpha=0.3)
plt.title("Review Length vs Sentiment")
plt.xlabel("Review Length")
plt.ylabel("Sentiment")
plt.show()